### ISSUE TITLE
speaktome-gspeech throwing errors in production

### ISSUE THREAD

**Issue by jbuck** [mozilla/gspeech#11]
@milescrabill and I were paged with a high memory usage alert in production. Looking at the log output of the service I see a significant amount of messages like `ERROR: TypeError: Cannot read property 'alternatives' of undefined` which corresponds to https://github.com/mozilla/gspeech/blob/3445ac45c3ea5fa3cfdb86bdbf7ad9bc24402725/index.js#L44 in the code. Looking at the [api documentation](https://github.com/googleapis/nodejs-speech#using-the-client-library) I see that google map()'s over the `results` array instead of only accessing the first index in the array - we should change the code to match.

**Comment by arku** [comment]
@jbuck Guess this issue can be closed as it is fixed in https://github.com/mozilla/gspeech/pull/12
